// PPTX export composable — generates OpenShift sizing report as .pptx browser download
// Plain TypeScript — NO Vue lifecycle hooks
// pptxgenjs dynamically imported to keep out of main bundle

import { useInputStore } from '@/stores/inputStore'
import { useCalculationStore } from '@/stores/calculationStore'
import type { ClusterConfig, ClusterSizing, NodeSpec } from '@/engine/types'

// Local types — avoid importing pptxgenjs types directly (dynamic import pattern)
interface TableCell {
  text: string
  options?: {
    bold?: boolean
    fill?: { color: string }
    color?: string
    align?: 'left' | 'center' | 'right'
    fontSize?: number
  }
}
type TableRow = TableCell[]

// ── Color constants (bare hex, NO # prefix) ──────────────────────────────────
const RH_RED = 'EE0000'
const RH_DARK = '151515'
const HEADER_BG = 'E8E8E8'
const WHITE = 'FFFFFF'

// ── Pure data-mapping helpers (testable without pptxgenjs) ───────────────────

type SummaryRow = { label: string; value: string }

export function buildArchSummaryData(
  cluster: ClusterConfig,
  totals: ClusterSizing['totals'],
): SummaryRow[] {
  return [
    { label: 'Topology', value: cluster.topology },
    { label: 'Environment', value: cluster.environment },
    { label: 'HA Required', value: cluster.haRequired ? 'Yes' : 'No' },
    { label: 'Total vCPU', value: String(totals.vcpu) },
    { label: 'Total RAM (GB)', value: String(totals.ramGB) },
    { label: 'Total Storage (GB)', value: String(totals.storageGB) },
  ]
}

function hdrCell(text: string): TableCell {
  return { text, options: { bold: true, fill: { color: HEADER_BG }, color: '000000' } }
}

function cell(text: string): TableCell {
  return { text }
}

export function buildBomTableRows(sizing: ClusterSizing): TableRow[] {
  const header: TableRow = [
    hdrCell('Node Type'),
    hdrCell('Count'),
    hdrCell('vCPU'),
    hdrCell('RAM (GB)'),
    hdrCell('Storage (GB)'),
  ]
  type NodeEntry = { label: string; spec: NodeSpec }
  const entries: NodeEntry[] = [
    { label: 'Control Plane', spec: sizing.masterNodes },
    ...(sizing.workerNodes ? [{ label: 'Workers', spec: sizing.workerNodes }] : []),
    ...(sizing.infraNodes ? [{ label: 'Infra Nodes', spec: sizing.infraNodes }] : []),
    ...(sizing.odfNodes ? [{ label: 'ODF Storage', spec: sizing.odfNodes }] : []),
    ...(sizing.rhacmWorkers ? [{ label: 'RHACM Hub', spec: sizing.rhacmWorkers }] : []),
    ...(sizing.virtWorkerNodes ? [{ label: 'Virt Workers', spec: sizing.virtWorkerNodes }] : []),
    ...(sizing.gpuNodes ? [{ label: 'GPU Nodes', spec: sizing.gpuNodes }] : []),
  ]
  const dataRows: TableRow[] = entries.map((e) => [
    cell(e.label),
    cell(String(e.spec.count)),
    cell(String(e.spec.vcpu)),
    cell(String(e.spec.ramGB)),
    cell(String(e.spec.storageGB)),
  ])
  const rhoaiRows: TableRow[] = sizing.rhoaiOverhead
    ? [
        [
          cell('RHOAI Overhead (KServe / DS Pipelines / Model Registry)'),
          cell('—'),
          cell(`+${sizing.rhoaiOverhead.vcpu}`),
          cell(`+${sizing.rhoaiOverhead.ramGB}`),
          cell('—'),
        ],
      ]
    : []
  return [header, ...dataRows, ...rhoaiRows]
}

// ── Main export function ──────────────────────────────────────────────────────

export async function generatePptxReport(): Promise<void> {
  const input = useInputStore()
  const calc = useCalculationStore()
  const clusterIdx = input.activeClusterIndex
  const cluster = input.clusters[clusterIdx] ?? input.clusters[0]
  const result = calc.clusterResults[clusterIdx] ?? calc.clusterResults[0]
  const sizing = result.sizing

  // Dynamic import — pptxgenjs stays out of main bundle
  const { default: PptxGenJS } = await import('pptxgenjs')
  const pptx = new PptxGenJS()

  pptx.layout = 'LAYOUT_WIDE'
  pptx.author = 'OpenShift Sizer'
  pptx.subject = 'OpenShift Sizing Report'
  pptx.title = 'OpenShift Architecture — ' + cluster.name

  // ── Slide 1: Architecture Summary ─────────────────────────────────────────
  const slide1 = pptx.addSlide()

  // Title bar
  slide1.addShape('rect', { x: 0, y: 0, w: '100%', h: 0.8, fill: { color: RH_RED } })
  slide1.addText('OpenShift Sizing Report', {
    x: 0.3,
    y: 0.1,
    w: 9,
    h: 0.6,
    fontSize: 22,
    bold: true,
    color: WHITE,
  })
  slide1.addText(cluster.name, {
    x: 0.3,
    y: 0.9,
    w: 9,
    h: 0.5,
    fontSize: 16,
    color: RH_DARK,
  })

  // Summary table
  const summaryRows = buildArchSummaryData(cluster, sizing.totals)
  const summaryTableData: TableRow[] = summaryRows.map((row) => [
    { text: row.label, options: { bold: true, fill: { color: HEADER_BG } } },
    { text: row.value },
  ])
  slide1.addTable(summaryTableData, {
    x: 0.5,
    y: 1.6,
    w: 9,
    colW: [4, 5],
    border: { type: 'solid', color: 'CCCCCC', pt: 0.5 },
    fontSize: 12,
  })

  // Footer
  slide1.addText(`Generated by OpenShift Sizer — ${new Date().toLocaleDateString()}`, {
    x: 0.3,
    y: 6.8,
    w: 9.4,
    h: 0.3,
    fontSize: 8,
    color: '888888',
    align: 'center',
  })

  // ── Slide 2: Bill of Materials ─────────────────────────────────────────────
  const slide2 = pptx.addSlide()

  slide2.addShape('rect', { x: 0, y: 0, w: '100%', h: 0.8, fill: { color: RH_RED } })
  slide2.addText('Bill of Materials', {
    x: 0.3,
    y: 0.1,
    w: 9,
    h: 0.6,
    fontSize: 22,
    bold: true,
    color: WHITE,
  })

  const bomRows = buildBomTableRows(sizing)
  slide2.addTable(bomRows, {
    x: 0.5,
    y: 1.0,
    w: 9,
    colW: [2.5, 1.5, 1.5, 1.5, 2],
    border: { type: 'solid', color: 'CCCCCC', pt: 0.5 },
    fontSize: 11,
  })

  slide2.addText(`Generated by OpenShift Sizer — ${new Date().toLocaleDateString()}`, {
    x: 0.3,
    y: 6.8,
    w: 9.4,
    h: 0.3,
    fontSize: 8,
    color: '888888',
    align: 'center',
  })

  // ── Download ───────────────────────────────────────────────────────────────
  const filename = `os-sizer-${cluster.name.replace(/\s+/g, '-').toLowerCase()}-${new Date().toISOString().split('T')[0]}.pptx`
  await pptx.writeFile({ fileName: filename })
}
